Given the following patient condition and the corresponding relevant medical guideline text (unformatted),
generate a guideline recommendation.

The condition details are given below. This includes the condition itself, along with associated encounters/medications
that the patient has taken already. Make sure the guideline recommendation is relevant.

**Patient Info:**
{patient_info}


**Condition Info:**
{condition_info}

**Matched Guideline Text(s):**
{guideline_text}